server:
  port: 8761

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8761
  server:
    wait-time-in-ms-when-sync-empty: 5